# Generated by Django 4.2.26 on 2025-11-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0002_alter_student_group_alter_student_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="teachers",
            field=models.ManyToManyField(
                blank=True, related_name="students", to="school.teacher"
            ),
        ),
    ]
