# Generated by Django 4.2.26 on 2025-11-05 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0004_auto_20251106_0120"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="teacher",
        ),
    ]
